import { NextRequest, NextResponse } from "next/server";
import dbConnect from "@/lib/mongodb";
import Ingredient from "@/models/Ingredient";
import IngredientAlias from "@/models/IngredientAlias";
import { levenshteinDistance } from "@/utils/levenshtein";
import { enrichUnmatchedIngredients } from "@/utils/ingredientEnrichment";

export const maxDuration = 60;

export async function POST(req: NextRequest) {
  try {
    await dbConnect();

    const body = await req.json();
    const extracted_ingredients: string[] = body.extracted_ingredients;

    if (!extracted_ingredients || !Array.isArray(extracted_ingredients)) {
      return NextResponse.json(
        { error: "Invalid request, expected extracted_ingredients array" },
        { status: 400 }
      );
    }

    // Fetch all ingredients and aliases once since the collection is small.
    const allIngredients = await Ingredient.find({}).lean();
    const allAliases = await IngredientAlias.find({}).lean();

    type MatchedRow = Record<string, unknown> & {
      raw: string;
      matched_name: string;
      id: string;
    };
    const matched: MatchedRow[] = [];
    let unmatched: string[] = [];
    const matchedNamesSet = new Set<string>();

    for (const raw of extracted_ingredients) {
      const rawLower = raw.toLowerCase().trim();
      if (!rawLower) continue;

      let found = null;

      // 1. Case-insensitive exact match
      found = allIngredients.find(ing => ing.name.toLowerCase() === rawLower);

      // 2. Fuzzy match (Levenshtein <= 2)
      if (!found) {
        found = allIngredients.find(ing => levenshteinDistance(ing.name.toLowerCase(), rawLower) <= 2);
      }

      // 3. Contains match
      if (!found) {
        found = allIngredients.find(ing =>
          ing.name.toLowerCase().includes(rawLower) ||
          rawLower.includes(ing.name.toLowerCase())
        );
      }

      // 4. Known-alias table
      if (!found) {
        const aliasMatch = allAliases.find(alias => alias.alias.toLowerCase() === rawLower);
        if (aliasMatch) {
          found = allIngredients.find(ing => ing.name === aliasMatch.matched_name);
        }
      }

      // 5. Alias fuzzy / contains
      if (!found) {
        const aliasMatch = allAliases.find(alias =>
          levenshteinDistance(alias.alias.toLowerCase(), rawLower) <= 2 ||
          alias.alias.toLowerCase().includes(rawLower) ||
          rawLower.includes(alias.alias.toLowerCase())
        );
        if (aliasMatch) {
          found = allIngredients.find(ing => ing.name === aliasMatch.matched_name);
        }
      }

      if (found) {
        if (!matchedNamesSet.has(found.name)) {
          matched.push({
            raw,
            matched_name: found.name,
            id: String(found._id),
            ...found, // return all fields from the new schema
          });
          matchedNamesSet.add(found.name);
        }
      } else {
        unmatched.push(raw);
      }
    }

    /* ──────────────────────────────────────────────────────────────────── */
    /* Auto-enrichment for unmatched ingredients via Gemini                 */
    /*                                                                      */
    /* The enrichment helper handles validation, retries and field-          */
    /* completion internally — this route only persists the result.          */
    /* ──────────────────────────────────────────────────────────────────── */

    if (unmatched.length > 0) {
      try {
        const generated = await enrichUnmatchedIngredients(unmatched);

        for (const newIng of generated) {
          try {
            const savedIng = await Ingredient.findOneAndUpdate(
              { name: newIng.name },
              { $set: newIng },
              { upsert: true, new: true, runValidators: true }
            );

            if (!savedIng) continue;

            // Map back to the closest raw OCR token so the UI can pair them.
            const lowerName = newIng.name.toLowerCase();
            const correspondingRaw =
              unmatched.find(u => {
                const ul = u.toLowerCase();
                return (
                  lowerName.includes(ul) ||
                  ul.includes(lowerName) ||
                  levenshteinDistance(ul, lowerName) <= 3
                );
              }) || newIng.name;

            if (!matchedNamesSet.has(savedIng.name)) {
              matched.push({
                raw: correspondingRaw,
                matched_name: savedIng.name,
                id: String(savedIng._id),
                ...savedIng.toObject(),
                _autoGenerated: true,
              });
              matchedNamesSet.add(savedIng.name);
            }

            // Remove the handled token from the unmatched list.
            unmatched = unmatched.filter(u => u !== correspondingRaw);
          } catch (saveErr) {
            console.error(
              "[identify] Failed to persist enriched ingredient:",
              newIng.name,
              saveErr
            );
          }
        }
      } catch (err) {
        console.error("[identify] Gemini enrichment failed:", err);
      }
    }

    return NextResponse.json({
      extracted_ingredients,
      matched,
      unmatched,
    });
  } catch (error: unknown) {
    console.error("Error identifying ingredients:", error);
    const details = error instanceof Error ? error.message : String(error);
    return NextResponse.json(
      { error: "Failed to identify ingredients", details },
      { status: 500 }
    );
  }
}
